export const availableTickers: Record<string, string> = {
  "Apple Inc. (AAPL)": "AAPL",
  "Johnson & Johnson (JNJ)": "JNJ",
  "Exxon Mobil Corporation (XOM)": "XOM",
  "JPMorgan Chase & Co. (JPM)": "JPM",
  "Procter & Gamble Co. (PG)": "PG",
  "Tesla, Inc. (TSLA)": "TSLA",
  "Alibaba Group (BABA)": "BABA",
  "Infosys Limited (INFY)": "INFY",
  "Rio Tinto Group (RIO)": "RIO",
  "SPDR S&P 500 ETF Trust (SPY)": "SPY",
  "Alphabet Inc. (Google) (GOOGL)": "GOOGL",
  "Microsoft Corporation (MSFT)": "MSFT",
  "Amazon.com, Inc. (AMZN)": "AMZN",
  "NVIDIA Corporation (NVDA)": "NVDA",
  "Intel Corporation (INTC)": "INTC",
  "Netflix, Inc. (NFLX)": "NFLX",
  "Walt Disney Company (DIS)": "DIS",
  "Visa Inc. (V)": "V",
  "Mastercard Incorporated (MA)": "MA",
  "Salesforce.com, Inc. (CRM)": "CRM",
  "PayPal Holdings, Inc. (PYPL)": "PYPL",
  "The Boeing Company (BA)": "BA",
  "General Electric Company (GE)": "GE",
  "Walmart Inc. (WMT)": "WMT",
  "Coca-Cola Company (KO)": "KO",
  "PepsiCo, Inc. (PEP)": "PEP",
  "McDonald's Corporation (MCD)": "MCD",
  "Archer-Daniels-Midland Company (ADM)": "ADM",
  "Cisco Systems, Inc. (CSCO)": "CSCO",
  "International Business Machines Corporation (IBM)": "IBM",
  "Home Depot, Inc. (HD)": "HD",
  "Lowe's Companies, Inc. (LOW)": "LOW",
  "Chevron Corporation (CVX)": "CVX",
  "Wells Fargo & Company (WFC)": "WFC",
  "Goldman Sachs Group, Inc. (GS)": "GS",
  "Morgan Stanley (MS)": "MS",
  "AT&T Inc. (T)": "T",
  "Verizon Communications Inc. (VZ)": "VZ",
  "UnitedHealth Group Incorporated (UNH)": "UNH",
  "CVS Health Corporation (CVS)": "CVS",
  "Abbott Laboratories (ABT)": "ABT",
  "Medtronic PLC (MDT)": "MDT",
  "Bristol-Myers Squibb Company (BMY)": "BMY",
  "Moody's Corporation (MCO)": "MCO",
  "Lockheed Martin Corporation (LMT)": "LMT",
  "Nike, Inc. (NKE)": "NKE",
  "Starbucks Corporation (SBUX)": "SBUX",
  "Target Corporation (TGT)": "TGT",
  "United Parcel Service, Inc. (UPS)": "UPS",
  "Lululemon Athletica Inc. (LULU)": "LULU",
  "Simon Property Group, Inc. (SPG)": "SPG",
} as const;
